config circle ci for deployment
bitmark-inc/docs pull request #54
Opened 2019-10-30 04:34 UTC by jollyjoker992

- Config CI for build and deploy latest HTML code to repo [bitmark-inc.github.io](https://github.com/bitmark-inc/bitmark-inc.github.io)

2019-10-30 05:10 UTC, araujobsd requested changes
This will never work!! igor will fail in master branch and the deployment will never run.
Or you add a logic to don't run igor on master branch and only run in branches, or all the issues must be fixed. 

A third option is to remove "igor" and let the "broken English" go wild.

2019-10-30 05:10 UTC, araujobsd commented on .circleci/config.yml
> -      # specify the version
Gratuitous change, here we specify the Golang version and I have add the comment for a reason.

2019-10-30 05:10 UTC, araujobsd commented on .circleci/config.yml
> -    working_directory: ~/docs-testing/
Another gratuitous change that should not be part of this diff.

2019-10-30 09:41 UTC, jollyjoker992 commented on .circleci/config.yml
> -      # specify the version
It's super common to get the meaning of that line. That's why i remove it. :)

2020-02-17 08:33 UTC, nodestory commented on tools/check-spelling.sh
> +    /^~~~|^ *```/{
@hxw I added another pattern here. Some code sections are wrapped by backticks.

2020-02-19 04:24 UTC, hxw commented on tools/check-spelling.sh
> +    /^~~~|^ *```/{
[[:space:]]*

2020-02-20 08:29 UTC, hxw approved these changes

2020-02-20 08:40 UTC, merged